account/urls.py
from django.urls import path
from account.views import SignUpView

urlpatterns = [
    # path('url_letter/', YOUR_VIEW_CLASS.as_view(), name='starts'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

goozs/urls.py
from django.urls import path
from goozs.views import (
    GoozsCreateView,
    GoozsIndexView,
)

urlpatterns = [
    path('', GoozsIndexView.as_view(), name='index'),
    path('register/', GoozsCreateView.as_view(), name='register'),
]

goozy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_setup.urls')),
    path('', include('goozs.urls')),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

goozs/models.py
from django.db import models

# Create your models here.

class Gooz(models.Model):
  name = models.CharField(max_length = 255)
  serial = models.CharField(max_length = 255)
  photo = models.ImageField(upload_to='documents/', default='df_img')
  registered_by = models.CharField(max_length = 255)
  uploaded_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
        return self.name

goozs/forms.py
from django import forms
from goozs.models import Gooz

account/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'account/signup.html'

goozs/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from goozs.models import Gooz

# Create your views here.


class GoozsIndexView(LoginRequiredMixin, ListView):
    login_url = '/account/login/'
    redirect_field_name = 'redirect_to'
    template_name = "index.html"
    paginate_by = 10

    def get_queryset(self):
        print(self.kwargs.get('username'))
        return Gooz.objects.filter(registered_by=self.request.user)



class GoozsCreateView(LoginRequiredMixin, CreateView):
    template_name = "register.html"
    login_url = '/account/login/'
    redirect_field_name = 'redirect_to'
    model = Gooz
    fields = ['name', 'serial', 'photo', 'registered_by']
    success_url = "/"



    def get_form(self):
        form = super(GoozsCreateView, self).get_form()
        form.fields['name'].label = '品名'
        form.fields['serial'].label = 'シリアル'

        return form

shell/templates/base.html
<!doctype html>
<head>
    <!-- UIkit CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">物品リスト</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="/">Goozy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-danger" href="/register">新規登録</a>
            </li>
        </ul>
    </div>
</nav>


      <div class="container">
        {% block body %}
        {% endblock %}
      </div>
  
      
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
      {% block script %}
      {% endblock %}
</body>
</html>

shell/templates/index.html
{% extends "page_base.html" %}
{% block body %}

<h1>管理物品リスト</h1>


<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">イメージ</th>
        <th scope="col">品名</th>
        <th scope="col">シリアル</th>
      </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
        <tr>
            <td>

                <img src="{{ obj.photo.url }}" class="media-object" height="200" loading="lazy">

            </td>
            <td>{{ obj.name }}</td>
            <td>{{ obj.serial }}</td>
        </tr>
        {% endfor %}
    </tbody>
  </table>

    
        <nav aria-label="Page navigation example">

            <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
                <!-- 前へ の部分 -->
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
        
                <!-- 数字の部分 -->
                {% for num in page_obj.paginator.page_range %}
                    {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}
        
                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
        
                <!-- 次へ の部分 -->
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        
        </nav>
{% endblock %}

shell/templates/page_base.html
<!doctype html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">物品リスト</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="/">Goozy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="btn btn-danger" href="/register">新規登録</a>
            </li>
        </ul>
    </div>
</nav>


      <div class="container">
        {% block body %}
        {% endblock %}
      </div>
  
      
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
      {% block script %}
      {% endblock %}
</body>
</html>

shell/templates/register.html
{% extends "page_base.html" %}
{% load widget_tweaks %}

{% block body %}

<div class="row">
    <h1>新規登録</h1>
</div>

<div class="row">
    <img id="preview" class="rounded mx-auto d-block" height="300" alt="選択された画像">

</div>


<form enctype="multipart/form-data" method="post" novalidate>{% csrf_token %}

    
    <div class="form-group">
        <div class="input-group">
            <label class="input-group-btn">
                <span class="btn btn-lg btn-primary">
                    Choose File{{form.photo|add_class:"form-control"|attr:"type:file"|attr:"id:file"|attr:"style:display:none"}}
                </span>
            </label>
        </div>
    </div>
    <div class="form-group">
        <label>品名</label>
        {{form.name|add_class:"form-control"}}
    </div>
    <div class="form-group">
        <label>シリアル</label>
        {{form.serial|add_class:"form-control"}}
        <input name="registered_by" maxlength="255" hidden required id="id_registered_by" value="{{user.get_username}}"">
    </div>

    <button type="submit" class="btn btn-primary">登録</button>
</form>


{% endblock %}

{% block script %}

<script>
$('#file').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

{% endblock %}

shell/templates/register_barcode.html
{% extends "page_base.html" %}
{% block body %}

<h1>新規登録</h1>
        <div>
            <button type="button" class="btn btn-primary" id="startButton">スキャン</button>
            <button type="button" class="btn btn-primary" id="resetButton">リセット</button>
        </div>

        <div>
            <video id="video" width="80%" height="400" style="margin-left: 10%;"></video>
        </div>

    

        <div id="sourceSelectPanel" style="display:none">
            <label for="sourceSelect">カメラを選択</label>
            <select id="sourceSelect" class="custom-select">
            </select>
        </div>

        <label>Result:</label>
        <pre><code id="result"></code></pre>

        
    
    
<script type="text/javascript" src="https://unpkg.com/@zxing/library@latest"></script>
<script type="text/javascript">
    window.addEventListener('load', function () {
        let selectedDeviceId;
        const codeReader = new ZXing.BrowserBarcodeReader()
        console.log('ZXing code reader initialized')
        codeReader.getVideoInputDevices()
            .then((videoInputDevices) => {
                const sourceSelect = document.getElementById('sourceSelect')
                selectedDeviceId = videoInputDevices[0].deviceId
                if (videoInputDevices.length > 1) {
                    videoInputDevices.forEach((element) => {
                        const sourceOption = document.createElement('option')
                        sourceOption.text = element.label
                        sourceOption.value = element.deviceId
                        sourceSelect.appendChild(sourceOption)
                    })

                    sourceSelect.onchange = () => {
                        selectedDeviceId = sourceSelect.value;
                    }

                    const sourceSelectPanel = document.getElementById('sourceSelectPanel')
                    sourceSelectPanel.style.display = 'block'
                }

                document.getElementById('startButton').addEventListener('click', () => {
                    codeReader.decodeOnceFromVideoDevice(selectedDeviceId, 'video').then((result) => {
                        console.log(result)
                        document.getElementById('result').textContent = result.text
                    }).catch((err) => {
                        console.error(err)
                        document.getElementById('result').textContent = err
                    })
                    console.log(`Started continous decode from camera with id ${selectedDeviceId}`)
                })

                document.getElementById('resetButton').addEventListener('click', () => {
                    document.getElementById('result').textContent = '';
                    codeReader.reset();
                    console.log('Reset.')
                })

            })
            .catch((err) => {
                console.error(err)
            })
    })
</script>

    

{% endblock %}